create database Retail

select * from Customer
select * from Transactions
select * from prod_cat_info

--Q1 What is the total number of rows in each of the 3 tables in the database?
select count(customer_id) as total_num_rows
from Customer

select count(prod_cat) as total_num_rows
from prod_cat_info

select count(transaction_id) as total_num_rows
from Transactions

--Q2 What is the total number of transactions that have a return? 
select count(transaction_id) as transactions
from Transactions
where Qty < 0

--Q3 As you would have noticed, the dates provided across the datasets are not in a 
--correct format. As first steps, pls convert the date variables into valid date formats 
--before proceeding ahead. 
select *, convert(date,tran_date,105) as date1 
from Transactions
  
--Q4 What is the time range of the transaction data available for analysis? Show the 
--output in number of days, months and years simultaneously in different columns.
  select DATEDIFF(day,max(tran_date), MIN(tran_date)) as diff_days,
  DATEDIFF(month,max(tran_date), min(tran_date)) as diff_month,
  DATEDIFF(year, max(tran_date), min(tran_date)) as Diff_years
  from Transactions

--Q5 Which product category does the sub-category “DIY” belong to? 
  select prod_cat
  from prod_cat_info
  where prod_subcat = 'DIY'

  --data analysis

  --Q1 Which channel is most frequently used for transactions?
  select count(store_type)as count_store, Store_type
  from Transactions
  group by Store_type
  order by count_store desc

  --Q2 What is the count of Male and Female customers in the database? 
select Gender,COUNT(gender) 
from Customer
group by Gender

--Q3 From which city do we have the maximum number of customers and how many? 
select count(city_code) as city_count, city_code
from Customer
group by city_code
order by city_code 

--Q4 How many sub-categories are there under the Books category? 
select count(prod_sub_cat_code) as count_subcat
from prod_cat_info
where prod_cat = 'Books'

--Q5 What is the maximum quantity of products ever ordered? 
select max(Qty) as max_qty
from Transactions
where Qty > 0

--Q6 What is the net total revenue generated in categories Electronics and Books?
select prod_cat, sum(total_amt) as tot_sales
from transactions a
left join prod_cat_info b
on a.prod_cat_code = b.prod_cat_code and a.prod_subcat_code = b.prod_sub_cat_code
where prod_cat in ('electronics','Books')
group by prod_cat


--Q7 How many customers have >10 transactions with us, excluding returns?
select cust_id as customer_id, count(transaction_id) as transaction_count
from transactions
where Qty > 0
group by cust_id
having count(transaction_id) > 10


--Q8 What is the combined revenue earned from the “Electronics” & “Clothing” 
--categories, from “Flagship stores”? 
 select prod_cat, sum(total_amt) as tot_sales
 from transactions as a
 inner join prod_cat_info as b
 on a.prod_cat_code = b.prod_cat_code and a.prod_subcat_code = b.prod_sub_cat_code
where store_type = 'flagship store' and prod_cat in ('electronics', 'clothing')
group by prod_cat

--Q9 What is the total revenue generated from “Male” customers in “Electronics” 
--category? Output should display total revenue by prod sub-cat. 
select prod_cat, Gender, prod_subcat, sum(total_amt) as tot_sales
from customer as a
inner join transactions as b
on a.customer_id = cust_id
inner join prod_cat_info as c
on b.prod_cat_code = c.prod_cat_code and b.prod_subcat_code = c.prod_sub_cat_code
where gender = 'M' and prod_cat = 'electronics'
group by prod_subcat, prod_cat, Gender


--Q10 What is percentage of sales and returns by product sub category; display only top 5
--sub categories in terms of sales? 
select top 5 prod_subcat, sum(total_amt) as tot_sales
from transactions as a
inner join prod_cat_info as b
on a.prod_cat_code = b.prod_cat_code and a.prod_subcat_code = b.prod_sub_cat_code
group by prod_subcat
order by tot_sales desc

--Q11 For all customers aged between 25 to 35 years find what is the net total revenue 
--generated by these consumers in last 30 days of transactions from max transaction 
--date available in the data?
select cust_id, sum(total_amt) as revenue from Transactions
where cust_id in
	(select customer_id from customer
	where datediff(year,CONVERT(date,Dob,103),GETDATE()) between 25 and 35)
	and CONVERT(date,tran_date,103)between DATEADD(day,-30,(select max(convert( date,tran_date,103)) from Transactions))
	and (select max(convert(date,tran_date,103)) from Transactions) 
	group by cust_id

--Q12 Which product category has seen the max value of returns in the last 3 months of 
--transactions?

select prod_cat,
sum(case when total_amt < 0 then total_amt else 0 end) [Return value] 
from Transactions z
inner join prod_cat_info y
on Z.prod_cat_code = Y.prod_cat_code
group by Y.prod_cat, tran_date
having tran_date > dateadd(month, -3, (select max(tran_date) from transactions))
order by [Return value] asc


--Q13 Which store-type sells the maximum products; by value of sales amount and by 
--quantity sold

select top 1 Store_type, sum(total_amt) as tot_sales, count(Qty) as Max_Qty
from Transactions 
group by Store_type
Having count(Qty) > 0
order by tot_sales, Max_Qty desc

--Q14 What are the categories for which average revenue is above the overall average

select prod_cat, Avg(total_amt) as Avg_sales
from Transactions as A
inner join prod_cat_info as B
on A.prod_cat_code = B.prod_cat_code and A.prod_subcat_code = B.prod_sub_cat_code
group by prod_cat
having AVg(total_amt) > (Select Avg(total_amt) from Transactions)

--15 Find the average and total revenue by each subcategory for the categories which 
--are among top 5 categories in terms of quantity sold.
select top 5 prod_subcat, prod_cat, Round(Avg(total_amt),2) as AVG_AMt, 
round(Sum(total_amt),2) as Tot_Amt,Count(Qty) as MAX_Qty 
from Transactions as A
inner join prod_cat_info as B
on A.prod_cat_code = B.prod_cat_code and A.prod_subcat_code = B.prod_sub_cat_code
Group by prod_subcat, prod_cat
Having Count(QTy) > 0
order by COunt(Qty)Desc


